# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0003_auto_20181017_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
